# Generated by Django 3.1.6 on 2021-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='external_page',
            field=models.URLField(blank=True),
        ),
    ]
