# Generated by Django 3.1.6 on 2021-05-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='like_page',
            new_name='link_page',
        ),
    ]
